services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_ROOT_PASSWORD=example
      - DB_NAME=sistema_de_votacao_api
      - JWT_SECRET=23cr3t0d3m41s
      - JWT_EXPIRES_IN=3600
      - PORT=3000
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  db:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=sistema_de_votacao_api
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
